# Generated by Django 2.2.1 on 2019-05-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('localidad', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
                ('precio_base', models.FloatField()),
                ('limite_personas', models.PositiveSmallIntegerField()),
                ('nro_direccion', models.PositiveIntegerField()),
                ('calle', models.CharField(max_length=100)),
                ('cant_habitaciones', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
