# Generated by Django 2.2.1 on 2019-05-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=20)),
                ('tarjeta_credito', models.CharField(max_length=16)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('fecha_nac', models.DateField()),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
                ('precio_base', models.FloatField()),
                ('limite_personas', models.PositiveSmallIntegerField()),
                ('nro_direccion', models.PositiveIntegerField()),
                ('calle', models.CharField(max_length=100)),
                ('cant_habitaciones', models.PositiveSmallIntegerField()),
                ('imagen_URL', models.URLField()),
            ],
            options={
                'unique_together': {('localidad', 'nro_direccion', 'calle')},
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_residencia', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='HSH.Residencia')),
            ],
            options={
                'unique_together': {('id_residencia', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSH.Reserva')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSH.Usuario')),
            ],
        ),
    ]
