# Generated by Django 2.2.1 on 2019-05-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='residencia',
            unique_together=set(),
        ),
    ]
