# Generated by Django 2.2.1 on 2019-05-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puja',
            unique_together=set(),
        ),
    ]
