# Generated by Django 2.2.1 on 2019-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='imagen_URL',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
