# Generated by Django 2.2.1 on 2019-06-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0002_auto_20190605_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_Normal', models.FloatField()),
                ('precio_Premium', models.FloatField()),
            ],
        ),
    ]
