# Generated by Django 2.2.1 on 2019-05-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0002_auto_20190517_1205'),
        ('HSH', '0002_auto_20190519_0333'),
    ]

    operations = [
    ]
