# Generated by Django 2.2.1 on 2019-05-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0002_residencia_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_residencia', models.ForeignKey(default='None', on_delete=django.db.models.deletion.SET_DEFAULT, to='HSH.Residencia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=20)),
                ('tarjeta_credito', models.CharField(max_length=16)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSH.Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('id_subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSH.Subasta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSH.Usuario')),
            ],
        ),
    ]
