# Generated by Django 2.2.1 on 2019-05-29 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0003_merge_20190519_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tarjeta_credito',
            new_name='nro_tarjeta_credito',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cod_seg_tarjeta',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_premium',
            field=models.BooleanField(default=False, verbose_name='status de usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_vencimiento_tarjeta',
            field=models.DateField(default=datetime.datetime(2019, 5, 29, 20, 6, 58, 743676, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='marca_tarjeta_credito',
            field=models.IntegerField(choices=[(1, 'VISA'), (2, 'MASTERCARD'), (3, 'CREDENCIAL'), (4, 'CARTA FRANCA'), (5, 'CABAL'), (6, 'DINERS'), (7, 'AMERICAN EXPRESS')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_titular_tarjeta',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='creditos',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
