# Generated by Django 2.2.1 on 2019-06-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0004_reserva_usuario_ganador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
    ]
