# Generated by Django 2.2.1 on 2019-05-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0004_auto_20190529_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='es_premium',
            field=models.BooleanField(default=False, verbose_name='Tipo de Usuario'),
        ),
    ]
