# Generated by Django 2.2.1 on 2019-05-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HSH', '0005_auto_20190529_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
